# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 078ac2c1b309849c1019e6522dfe9451200466c4158fa7c0abe2f9a773a322a66a829111903b46db6eb89c164903b78674c175b27cc5edf2b3a577cbd0ff210c

test:
  secret_key_base: 369373a146c958f4217640d40e486f7e44da31ba6d69ba400887122fc35a8bd5f5c9db351ed88e1f52a9ee02c55e780ef29f406e557583021ae0eb9cf1dedb76

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
